# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Views\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 450)
        Form.setMinimumSize(QtCore.QSize(470, 450))
        Form.setMaximumSize(QtCore.QSize(470, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/logo2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-40, -10, 541, 491))
        self.widget.setStyleSheet("QPushButton#pushButton, #btn_registrar_usuario,#btn_asistencia{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0  #0f2dc2, stop:1 #5c687b);\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover, #btn_registrar_usuario:hover, #btn_asistencia:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#pushButton:pressed, #btn_registrar_usuario:pressed, #btn_asistencia:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#c4343c;\n"
"}\n"
"\n"
"#label_7, #label_8{\n"
"    color:rgba(0, 0, 0, 210);\n"
"}\n"
"\n"
"QPushButton#btn_recuperar_clave {\n"
"    color:rgba(0, 0, 0, 210);\n"
"    border:none;\n"
"}\n"
"QPushButton#btn_recuperar_clave:hover {\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));;\n"
"}\n"
"\n"
"QPushButton#btn_recuperar_clave:pressed {\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:#c4343c;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 49, 231, 411))
        self.label.setStyleSheet("border-image: url(:/icon/img/intento2.jpg);\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 49, 280, 411))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0, 30 ) ;\n"
"border-bottom-left-radius:50px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 49, 240, 411))
        self.label_3.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(295, 80, 190, 40))
        self.label_5.setMinimumSize(QtCore.QSize(190, 0))
        self.label_5.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(295, 150, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(295, 215, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(295, 295, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 230, 130))
        self.label_6.setStyleSheet("background-color:rgba(0, 0, 0, 75);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 80, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(50, 140, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_10.setObjectName("label_10")
        self.btn_registrar_usuario = QtWidgets.QPushButton(self.widget)
        self.btn_registrar_usuario.setGeometry(QtCore.QRect(270, 50, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.btn_registrar_usuario.setFont(font)
        self.btn_registrar_usuario.setStyleSheet("")
        self.btn_registrar_usuario.setObjectName("btn_registrar_usuario")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(300, 340, 182, 108))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.btn_recuperar_clave = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_recuperar_clave.setMinimumSize(QtCore.QSize(70, 0))
        self.btn_recuperar_clave.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_recuperar_clave.setFont(font)
        self.btn_recuperar_clave.setObjectName("btn_recuperar_clave")
        self.horizontalLayout.addWidget(self.btn_recuperar_clave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_asistencia = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_asistencia.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_asistencia.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_asistencia.setObjectName("btn_asistencia")
        self.horizontalLayout_3.addWidget(self.btn_asistencia)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_1 = QtWidgets.QLabel(self.widget)
        self.label_1.setGeometry(QtCore.QRect(40, 9, 471, 41))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap(".\\Views\\../Resources/img/cabecera.png"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Iniciar Sesión"))
        self.label_5.setText(_translate("Form", "Iniciar Sesión"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Usuario"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Contraseña"))
        self.pushButton.setText(_translate("Form", "I n i c i a r  S e s i ó n"))
        self.label_9.setText(_translate("Form", "S.A.M"))
        self.label_10.setText(_translate("Form", "Hola, \n"
"Bienvenido al Sistema \n"
"Automatizado de Monitoreo.\n"
""))
        self.btn_registrar_usuario.setText(_translate("Form", "+"))
        self.label_7.setText(_translate("Form", "¿Olvidastes tu"))
        self.btn_recuperar_clave.setText(_translate("Form", "Contraseña ?"))
        self.btn_asistencia.setText(_translate("Form", "Marcar Asistencia"))
import Resources.resource_rc
